# Generated by Django 3.2.3 on 2021-06-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('addressline1', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('addressline2', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('addressline3', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('pic', models.ImageField(blank=True, default=None, null=True, upload_to='images')),
            ],
        ),
    ]
