# Generated by Django 3.2.3 on 2021-06-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='postcode',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
