# Generated by Django 3.2.3 on 2021-06-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_seller_postcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='username',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
