# Generated by Django 3.2.3 on 2021-07-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0006_auto_20210705_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color6',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color7',
        ),
        migrations.RemoveField(
            model_name='product',
            name='l',
        ),
        migrations.RemoveField(
            model_name='product',
            name='m',
        ),
        migrations.RemoveField(
            model_name='product',
            name='s',
        ),
        migrations.RemoveField(
            model_name='product',
            name='xl',
        ),
        migrations.RemoveField(
            model_name='product',
            name='xs',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, default='red', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, default='xs', max_length=5, null=True),
        ),
    ]
