# Generated by Django 3.2.3 on 2021-07-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_alter_product_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('byid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('postcode', models.IntegerField(blank=True, default=None, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('addressline1', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('addressline2', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('addressline3', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('pic', models.FileField(blank=True, default=None, null=True, upload_to='images')),
            ],
        ),
    ]
