# Generated by Django 3.2.4 on 2021-07-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='q',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
