# Generated by Django 3.2.4 on 2021-07-28 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_alter_checkout_q'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='q',
        ),
    ]
