# Generated by Django 3.2.4 on 2021-07-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0015_checkout_q'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='q',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
