# Generated by Django 3.2.5 on 2021-07-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0016_alter_checkout_q'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
