# Generated by Django 3.2.5 on 2021-08-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0017_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='otp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
