# Generated by Django 3.2.5 on 2021-08-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0019_seller_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='mode',
            field=models.CharField(default='cod', max_length=20),
        ),
    ]
